NAME = phonebook
SRCS = main.cpp phonebook.cpp
CMP = c++
FLAGS = -Wall -Wextra -Werror

all:$(NAME)

$(NAME):
	$(CMP) $(FLAGS) $(SRCS) -o $(NAME)

clean:
	rm -f $(NAME)

fclean : clean

re: clean $(NAME)